### ISSUE TITLE
Turtles dont render correctly.

### ISSUE THREAD

**Issue by matty45** [mystiacraft/cc-tweaked-fabric#1]
https://i.imgur.com/v5p9lGx.png

For some reason the turtles appear to be missing textures when placed.

**Comment by parly** [comment]
Hello, thank you for reporting the bug!

Are you using OptiFabric by any chance? I'm currently looking for a workaround in that case...

**Comment by matty45** [comment]
Ah, that must be the problem! ill turn optifabric off and see if that fixes anything

**Comment by matty45** [comment]
Yup! it was optifine/optifabric.

**Comment by parly** [comment]
Thanks for sharing the result! I'll continue investigating this issue.

**Comment by Eliteneet** [comment]
Was there any headway on this issue? Facing the same problem on the latest version.

**Comment by parly** [comment]
I have finally identified the cause, so now working on a fix for this. I should be able to release it in a few hours.

**Comment by parly** [comment]
Fixed in 1.83.2+build.5. If the problem persists, please let me know by reopening this issue or creating a new one.
