### ISSUE TITLE
NoSuchMethodError 

### ISSUE THREAD

**Issue by hugeblank** [mystiacraft/cc-tweaked-fabric#14]
Discovered this gem while working in a dev environment. I'm not sure if it's the HTTP API but I feel like that would be a reasonable candidate to start with. I think what surprises me the most is that there was no traceback provided in the console.

<img width="778" alt="image" src="https://user-images.githubusercontent.com/16393543/66806313-18ee5880-eedc-11e9-8af8-8e0b18385c35.png">

 - Minecraft version: 1.14.4
 - CC: Tweaked version: 1.82.3
 - Run command:
```
wget https://raw.githubusercontent.com/hugeblank/qs-cc/master/src/gget.lua /lib/gget.lua
```
behold the error

**Comment by SquidDev** [comment]
The issue is here that the compiled code is using `ByteBuffer.clear()` (which only appeared on Java 9), rather than `Buffer.clear()`. Yay for `javac` I guess :/.

I guess the solution here is either to cast to `Buffer` before clearing, or for mystiacraft to downgrade to JDK 8.

**Comment by hugeblank** [comment]
Just a by the way, this appears to have fixed itself in my dev environment, and I haven't observed it in production. Don't know if it was something on my end or what, but it seems inconsistent.

**Comment by parly** [comment]
It seems that my .jar release doesn't contain that method call. That said, it's inconvenient to compile with Java 9+. I will add casts to `Buffer` later as @SquidDev said.
Thank you for pointing it out!
