### ISSUE TITLE
Commands Incorrectly Parsed

### ISSUE THREAD

**Issue by hugeblank** [mystiacraft/cc-tweaked-fabric#15]
- MC 1.14.4
 - CCTF 1.83.2 build 7
 - Reproduction steps: 
run command in Lua REPL `commands.exec("data get entity <username>")` where username is your username.

Expected result:
A fat brick of text with the mojson formatted NBT data.

Actual result:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/16393543/66996848-45de6f00-f086-11e9-8c6e-94037ea99d02.png">

**Comment by hugeblank** [comment]
You’re good! If I can find the time myself I’ll make a PR for it.

**Comment by parly** [comment]
Fixed in #17.
