### ISSUE TITLE
Unable to change monitor renderer.

### ISSUE THREAD

**Issue by RubenHetKonijn** [mystiacraft/cc-tweaked-fabric#24]
So I have this problem that i'm unable to change the monitor renderer, in forge i would've just gone to mod list and changed it there, but i can't see an option to change it. Even in the `computercraft.json` file it doesn't show anything about the monitor renderer.

**Comment by SquidDev** [comment]
It's probably worth reporting this [on this repository instead](https://github.com/Zundrel/cc-tweaked-fabric/), as that is the more recent version.

**Comment by RubenHetKonijn** [comment]
Done: https://github.com/Zundrel/cc-tweaked-fabric/issues/17
