### ISSUE TITLE
All turtle functions hang

### ISSUE THREAD

**Issue by BinaryBurgr** [mystiacraft/cc-tweaked-fabric#9]
- Minecraft: 1.14.4
 - Fabric Loader: 0.6.2+build.166
 - Fabric API: 0.4.0+build.240
 - CC: Tweaked: 1.83.2+build.4 and build.5
 - Detailed reproduction steps: Since build 4, all turtle functions (dig, place, refuel, detect, etc) hang and do nothing forever, requiring termination of the program. I went back to 1.83.2+build.3 and it worked fine again.

**Comment by parly** [comment]
Fixed in 1.83.2+build.6. Thank you for reporting it and sorry for the inconvenience.

**Comment by BinaryBurgr** [comment]
Awesome, thanks!
